server/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('idealist.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/idealist/urls.py
from django.urls import path
from . import views

app_name = 'ideas'

urlpatterns = [
    path('', view=views.idea_list, name='idealist'),
    path('idea/<int:idea_id>/', view=views.idea_detail, name='detail'),
    path('idea/create/', view=views.create_idea, name='create'),
    path('idea/update/<int:idea_id>/', view=views.idea_update, name='update'),
    path('idea/delete/<int:idea_id>/', view=views.idea_delete, name='delete'),

    path('devtool/create/', view=views.create_tool, name='create_tool'),
    path('devtool/', view=views.devtool_list, name='devtoollist'),
    path('devtool/<int:tool_id>/', view=views.devtool_detail, name='devtooldetail'),
    path('devtool/update/<int:tool_id>/', view=views.tool_update, name='tool_update'),
    path('devtool/delete/<int:tool_id>/', view=views.tool_delete, name='tool_delete'),

    path('plus_interest/',view=views.plus_view, name="plus_view"),
    path('minus_interest/',view=views.minus_view, name="minus_view"),
]

server/idealist/models.py
from django.db import models

class DevTool(models.Model):
    name=models.CharField(verbose_name='이름', max_length=100)
    kind=models.CharField(verbose_name='종류', max_length=100)
    description=models.TextField(verbose_name='개발툴 설명')

    def __str__(self):
        return self.name

# Create your models here.
class Idea(models.Model):
    title = models.CharField(verbose_name='아이디어명', max_length=100)
    image = models.ImageField(verbose_name='대표 사진', blank=True, null=True)
    content = models.TextField(verbose_name='아이디어 설명')
    interest = models.IntegerField(verbose_name='아이디어 관심도', default=0)
    devtool = models.ForeignKey(DevTool, related_name='devtool', verbose_name='예상 개발툴', on_delete=models.CASCADE )

    def __str__(self):
        return self.title

server/idealist/forms.py
from django import forms
from .models import Idea
from .models import DevTool


class IdeaForm(forms.ModelForm):

    # 해당 모델 자체의 정보를 담는 네임스페이스 클래스
    # https://stackoverflow.com/questions/57241617/what-is-exactly-meta-in-django
    class Meta:
        model = Idea
        fields = '__all__'

class DevToolForm(forms.ModelForm):
    class Meta:
        model = DevTool
        fields = '__all__'

class IdeaUpdate(forms.ModelForm):
    class Meta:
        model = Idea
        fields = '__all__'

class ToolUpdate(forms.ModelForm):
    class Meta:
        model = DevTool
        fields = '__all__'

server/idealist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Idea,DevTool
from .forms import IdeaForm,DevToolForm,IdeaUpdate,ToolUpdate
from django.views.generic.edit import UpdateView
from django.urls import reverse
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.


def idea_list(request):
    '''
    Read(R)
    아이디어들을 불러와서 리스트형태로 보여준다
    '''
    ideas = Idea.objects.all()  # 이 부분이 READ
    ctx = {'ideas': ideas}
    return render(request, template_name='idealist/list.html', context=ctx)

def idea_detail(request, idea_id):
    '''
    Read(R)
    특정 아이디어를 불러와서 상세정보를 보여준다
    '''
    idea = Idea.objects.get(id=idea_id)
    ctx = {'idea': idea}

    return render(request, template_name='idealist/detail.html', context=ctx)

def create_idea(request):
    '''
    Create(C)
    포스트를 새로 생성한다
    request method ==> GET(url입력), POST(저장하기) 생활코딩 보기
    '''
    if request.method == 'POST':
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            idea = form.save()
            return redirect('ideas:detail', idea.id)
    else:
        form = IdeaForm()
        ctx = {'form': form}
        return render(request, template_name='idealist/idea_form.html', context=ctx)

def idea_update(request, idea_id):
    idea = Idea.objects.get(id=idea_id)

    if request.method == 'POST':
        form = IdeaUpdate(request.POST, request.FILES)
        if form.is_valid():
            idea.title=form.cleaned_data['title']
            idea.image=form.cleaned_data['image']
            idea.content=form.cleaned_data['content']
            idea.interest=form.cleaned_data['interest']
            idea.devtool=form.cleaned_data['devtool']
            idea.save()
            return redirect('ideas:detail', idea.id)
    else:
        form = IdeaUpdate(instance=idea)
        return render(request, 'idealist/idea_update.html', {'form':form})


def idea_delete(request, idea_id):
    
    idea = get_object_or_404(Idea, pk=idea_id)

    if request.method == "GET":
        return redirect('ideas:detail', idea.id)
    elif request.method == "POST":
        idea.delete()
        return redirect('ideas:idealist')


def devtool_list(request):
    '''
    Read(R)
    아이디어들을 불러와서 리스트형태로 보여준다
    '''
    tools = DevTool.objects.all()  # 이 부분이 READ
    ctx = {'tools': tools}
    return render(request, template_name='idealist/tool_list.html', context=ctx)

def create_tool(request):
    if request.method == 'POST':
        form = DevToolForm(request.POST, request.FILES)
        if form.is_valid():
            devtool = form.save()
            return redirect('ideas:devtooldetail', devtool.id)
    else:
        form = DevToolForm()
        ctx = {'form': form}
        return render(request, template_name='idealist/tool_form.html', context=ctx)

def devtool_detail(request, tool_id):
    tool = DevTool.objects.get(id=tool_id)
    ctx = {'tool': tool}
    return render(request, template_name='idealist/tool_detail.html', context=ctx)


def tool_delete(request, tool_id):
    
    tool = get_object_or_404(DevTool, pk=tool_id)

    if request.method == "GET":
        return redirect('ideas:devtooldetail', tool.id)
    elif request.method == "POST":
        tool.delete()
        return redirect('ideas:devtoollist')
        

def tool_update(request, tool_id):
    tool = DevTool.objects.get(id=tool_id)

    if request.method == 'POST':
        form = ToolUpdate(request.POST, request.FILES)
        if form.is_valid():
            tool.name=form.cleaned_data['name']
            tool.kind=form.cleaned_data['kind']
            tool.description=form.cleaned_data['description']
            tool.save()
            return redirect('ideas:devtooldetail', tool.id)
    else:
        form = ToolUpdate(instance=tool)
        return render(request, 'idealist/tool_update.html', {'form':form})

@csrf_exempt
def plus_view(request):
    value = request.POST.get("value")
    idea = Idea.objects.get(id=str(value))
    idea.interest+=1
    idea.save()

    resp=json.dumps(idea.interest)
    return HttpResponse(resp, content_type="application/json")

@csrf_exempt
def minus_view(request):
    value = request.POST.get("value")
    idea = Idea.objects.get(id=str(value))
    idea.interest-=1
    idea.save()

    resp=json.dumps(idea.interest)
    return HttpResponse(resp, content_type="application/json")

server/idealist/templates/idealist/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'idealist/detail_style.css' %}">
    <title>아이디어 디테일</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar_logo">
            <a href="{% url 'ideas:idealist' %}"><u>My SW Idea Manage</u></a>
        </div>
        <ul class="navbar_menu">
            <li><a href="{% url 'ideas:create' %}">아이디어 등록</a></li>
            <li><a href="{% url 'ideas:idealist' %}">아이디어 관리</a></li>
            <li><a href="{% url 'ideas:create_tool' %}">개발툴 등록</a></li>
            <li><a href="{% url 'ideas:devtoollist' %}">개발툴 관리</a></li>
        </ul>
    </nav>

    <div class="idea_content" style="background-color:black">
        <div class="idea_title">
            <h1 style="color:aquamarine">Idea Detail</h1>
            <span style="color:#FFFFFF">아이디어 세부내용 페이지 입니다. 당신이 구현하려 한 아이디어들을 자세히 살펴보세요.</span>
        </div>
        <hr width=100% color="#808080">
        <div class="one_idea">
            <div class="one_idea_image">
                {% if idea.image %}
                    <img src = "{{ idea.image.url }}" alt="" height="100%">
                {% endif %}
            </div>
            <div class="one_idea_detail">
                <h2 style="color:#FF7F00"><u>{{idea.title}}</u></h2>
                <p>1) 아이디어 관심도:</p>
                <p><u>{{idea.interest}}</u></p>
                <p>2) 예상 개발 툴:</p>
                <a href="{% url 'ideas:devtooldetail' idea.devtool.id %}"><p style="color:#FF7F00"><u>{{idea.devtool}}</u></p></a>
                <p>3) 아이디어 설명:</p>
                <p><u>{{idea.content}}</u></p>
            </div>
        </div>
        <div class="buttons">
            <form action="{% url 'ideas:delete' idea.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="삭제" style="cursor: pointer;">
            </form>
            <a href="{% url 'ideas:idealist' %}"><button style="cursor: pointer;">목록</button></a>
            <a href="{% url 'ideas:update' idea.id %}"><button style="cursor: pointer;">수정</button></a>
        </div>
    </div>
</body>
</html>

server/idealist/templates/idealist/idea_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'idealist/form_style.css' %}">
    <title>아이디어 등록</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar_logo">
            <a href="{% url 'ideas:idealist' %}"><u>My SW Idea Manage</u></a>
        </div>
        <ul class="navbar_menu">
            <li><a href="{% url 'ideas:create' %}">아이디어 등록</a></li>
            <li><a href="{% url 'ideas:idealist' %}">아이디어 관리</a></li>
            <li><a href="{% url 'ideas:create_tool' %}">개발툴 등록</a></li>
            <li><a href="{% url 'ideas:devtoollist' %}">개발툴 관리</a></li>
        </ul>
    </nav>
    

    <div class="idea_content" style="background-color:black">
        <div class="idea_title">
            <h1 style="color:aquamarine">Idea Register</h1>
            <span style="color:#FFFFFF">아이디어 등록 페이지입니다. 당신의 아이디어를 잊지 말고 기록하세요!</span>
        </div>
        <hr width=100% color="#808080">
        <div class="inputs">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="SUBMIT">
            </form>
        </div>
    </div>
</body>

</html>

server/idealist/templates/idealist/idea_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'idealist/form_style.css' %}">
    <title>아이디어 등록</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar_logo">
            <a href="{% url 'ideas:idealist' %}"><u>My SW Idea Manage</u></a>
        </div>
        <ul class="navbar_menu">
            <li><a href="{% url 'ideas:create' %}">아이디어 등록</a></li>
            <li><a href="{% url 'ideas:idealist' %}">아이디어 관리</a></li>
            <li><a href="{% url 'ideas:create_tool' %}">개발툴 등록</a></li>
            <li><a href="{% url 'ideas:devtoollist' %}">개발툴 관리</a></li>
        </ul>
    </nav>
    

    <div class="idea_content" style="background-color:black">
        <div class="idea_title">
            <h1 style="color:aquamarine">Idea Detail Update</h1>
            <span style="color:#FFFFFF">아이디어 세부내용 수정 페이지 입니다. 아이디어를 구체화하거나 내용을 변경해 보아요.</span>
        </div>
        <hr width=100% color="#808080">
        <div class="inputs">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="SUBMIT">
            </form>
        </div>
    </div>
</body>

</html>

server/idealist/templates/idealist/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" type="text/css" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'idealist/list_style.css' %}">
    <title>Document</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar_logo">
            <a href="{% url 'ideas:idealist' %}"><u>My SW Idea Manage</u></a>
        </div>
        <ul class="navbar_menu">
            <li><a href="{% url 'ideas:create' %}">아이디어 등록</a></li>
            <li><a href="{% url 'ideas:idealist' %}">아이디어 관리</a></li>
            <li><a href="{% url 'ideas:create_tool' %}">개발툴 등록</a></li>
            <li><a href="{% url 'ideas:devtoollist' %}">개발툴 관리</a></li>
        </ul>
    </nav>

    <div class="idea_content" style="background-color:black">
        <div class="idea_title">
            <h1 style="color:aquamarine">Idea list</h1>
            <span style="color:#FFFFFF">나의 아이디어를 잊지 말고 기록해보세요</span>
        </div>
        <hr width=100% color="#808080">
        <div class="ideas">
        {% for idea in ideas %}
                <div class="one_idea" style="background-color: rgb(187, 255, 255);">
                    <div>
                        {% if idea.image %}
                        <img src = "{{ idea.image.url }}" alt="" height="250px" width="250px">
                        {% endif %}
                    </div>
                    <h2><a href="{% url 'ideas:detail' idea.id %}" style="color:black">{{ idea.title }}</a></h2>
                    <span>예상 개발 툴: {{ idea.devtool }}</span><br>
                    <span id="interest">아이디어 관심도: {{ idea.interest }}</span>
                    <button type="button" onclick="plus({{ idea.id }});">+</button>
                    <button type="button" onclick="minus({{ idea.id }});">-</button>
                </div>
        {% endfor %}
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        function plus(id){ 
            $.ajax({ 
                    url:'/plus_interest/',
                    type:"POST",
                    data : { 'value' : id},
                    success:function(response){
                        $('#interest').html('아이디어 관심도: '+ response)
                }
            }) 
        };
        function minus(id){ 
            $.ajax({ 
                    url:'/minus_interest/',
                    type:"POST",
                    data : { 'value' : id},
                    success:function(response){
                        $('#interest').html('아이디어 관심도: '+ response)
                }
            }) 
        };
    </script>


</body>
</html>

server/idealist/templates/idealist/tool_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'idealist/tool_detail.css' %}">
    <title>개발툴 디테일</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar_logo">
            <a href="{% url 'ideas:idealist' %}"><u>My SW Idea Manage</u></a>
        </div>
        <ul class="navbar_menu">
            <li><a href="{% url 'ideas:create' %}">아이디어 등록</a></li>
            <li><a href="{% url 'ideas:idealist' %}">아이디어 관리</a></li>
            <li><a href="{% url 'ideas:create_tool' %}">개발툴 등록</a></li>
            <li><a href="{% url 'ideas:devtoollist' %}">개발툴 관리</a></li>
        </ul>
    </nav>

    <div class="tool_content" style="background-color:black">
        <div class="tool_title">
            <h1 style="color:aquamarine">DevTool Detail</h1>
            <span style="color:#FFFFFF">개발들 세부내용 페이지 입니다. 자신이 다룰 수 있는 개발툴에 대한 상세내용을 확인해 보아요.</span>
        </div>
        <div class="one_tool">
            <div class="one_tool_content">
                <h1 style="color:#FF7F00">{{tool.name}}</h1>
                <span>{{tool.kind}}</span><br>
                <span>{{tool.description}}</span>
            </div>
            
            <hr width=100% color="#808080" style="margin: 20px 0px">
            
            <div class="one_tool_foreign">
                <span style="color:#FF7F00">> 만들 수 있는 SW 목록</span><br>
                {% for idea in tool.devtool.all %}
                    {{idea.title}}<br>
                {% endfor %}
            </div>
        </div>
        <div class="buttons">
            <form action="{% url 'ideas:tool_delete' tool.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="삭제" style="cursor: pointer;">
            </form>
            <a href="{% url 'ideas:devtoollist' %}"><button style="cursor: pointer;">목록</button></a>
            <a href="{% url 'ideas:tool_update' tool.id %}"><button style="cursor: pointer;">수정</button></a>
        </div>
    </div>
</body>
</html>

server/idealist/templates/idealist/tool_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'idealist/form_style.css' %}">
    <title>개발툴 등록</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar_logo">
            <a href="{% url 'ideas:idealist' %}"><u>My SW Idea Manage</u></a>
        </div>
        <ul class="navbar_menu">
            <li><a href="{% url 'ideas:create' %}">아이디어 등록</a></li>
            <li><a href="{% url 'ideas:idealist' %}">아이디어 관리</a></li>
            <li><a href="{% url 'ideas:create_tool' %}">개발툴 등록</a></li>
            <li><a href="{% url 'ideas:devtoollist' %}">개발툴 관리</a></li>
        </ul>
    </nav>
    

    <div class="idea_content" style="background-color:black">
        <div class="idea_title">
            <h1 style="color:aquamarine">DevTool Register</h1>
            <span style="color:#FFFFFF">개발툴 등록 페이지입니다. 자신이 다룰 수 있는 개발툴을 등록해 보세요.</span>
        </div>
        <hr width=100% color="#808080">
        <div class="inputs">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="id_name">>> 이름:<br></label><input type="text" name="name" maxlength="100" required id="id_name"><br>
                <label for="id_kind">>> 종류:<br></label><input type="text" name="kind" maxlength="100" required id="id_kind"><br>
                <label for="id_description">>> 개발툴 설명:<br></label><textarea name="description" cols="40" rows="10" required id="id_description"></textarea><br>
                <input type="submit" value="SUBMIT">
            </form>
        </div>
    </div>
</body>

</html>

server/idealist/templates/idealist/tool_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" type="text/css" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'idealist/tool_list_style.css' %}">
    <title>Document</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar_logo">
            <a href="{% url 'ideas:idealist' %}"><u>My SW Idea Manage</u></a>
        </div>
        <ul class="navbar_menu">
            <li><a href="{% url 'ideas:create' %}">아이디어 등록</a></li>
            <li><a href="{% url 'ideas:idealist' %}">아이디어 관리</a></li>
            <li><a href="{% url 'ideas:create_tool' %}">개발툴 등록</a></li>
            <li><a href="{% url 'ideas:devtoollist' %}">개발툴 관리</a></li>
        </ul>
    </nav>

    <div class="tool_content" style="background-color:black">
        <div class="tool_title">
            <h1 style="color:aquamarine">DevTool list</h1>
            <span style="color:#FFFFFF">개발툴 목록 페이지 입니다. 자신이 사용가능한 개발툴의 목록을 확인해 보세요.</span>
        </div>
        <hr width=100% color="#808080">
        <div class="tools">
        {% for tool in tools %}
                <div class="one_tool" style="background-color: rgb(187, 255, 255);">
                    <h2><a href="{% url 'ideas:devtooldetail' tool.id %}" style="color:black">{{ tool.name }}</a></h2>
                    <hr width=100% color="#FF7F00" style="height:3px">
                    <span>{{ tool.kind }}</span><br>
                    <p>{{ tool.description }}</p>
                </div>
        {% endfor %}
        </div>
    </div>
</body>
</html>

server/idealist/templates/idealist/tool_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'idealist/form_style.css' %}">
    <title>개발툴 수정</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar_logo">
            <a href="{% url 'ideas:idealist' %}"><u>My SW Idea Manage</u></a>
        </div>
        <ul class="navbar_menu">
            <li><a href="{% url 'ideas:create' %}">아이디어 등록</a></li>
            <li><a href="{% url 'ideas:idealist' %}">아이디어 관리</a></li>
            <li><a href="{% url 'ideas:create_tool' %}">개발툴 등록</a></li>
            <li><a href="{% url 'ideas:devtoollist' %}">개발툴 관리</a></li>
        </ul>
    </nav>
    

    <div class="idea_content" style="background-color:black">
        <div class="idea_title">
            <h1 style="color:aquamarine">DevTool Detail Update</h1>
            <span style="color:#FFFFFF">개발툴 세부내용 수정 페이지 입니다. 개발툴에 대해 수정사항이 있으면 고쳐보아요.</span>
        </div>
        <hr width=100% color="#808080">
        <div class="inputs">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="SUBMIT">
            </form>
        </div>
    </div>
</body>

</html>